blank_issues_enabled: true
contact_links:
  - name: Contact Lead Developer
    url: https://scratch.mit.edu/users/-Archon-/
    about: Please visit the lead developer's Scratch profile to ask questions about the repo. 
